version: '3.8'

services:
  # FastAPI 애플리케이션 서비스를 정의합니다.
  fastapi_app:
    # 현재 디렉토리의 Dockerfile을 사용하여 빌드합니다.
    build:
      context: .
      dockerfile: Dockerfile
    # 컨테이너의 이름을 'fastapi_app'으로 지정합니다.
    container_name: fastapi_app
    # 호스트와 컨테이너의 파일 시스템을 공유하기 위해 볼륨을 설정합니다.
    volumes:
      - .:/app
    # FastAPI 애플리케이션을 실행하는 데 필요한 환경 변수를 설정합니다.
    environment:
      - PYTHONUNBUFFERED=1
    # 컨테이너 내부에서 포트 8000을 노출합니다.
    ports:
      - "8000:8000"
